package com.mobdeve.s17.abary.inorafael.mco2

object SpotifyTracks {

    val allTracks = listOf(
        // Spotify Tracks - play when pressed
        "https://open.spotify.com/track/3yWuTOYDztXjZxdE2cIRUa",
        "https://open.spotify.com/track/0WbMK4wrZ1wFSty9F7FCgu",
        "https://open.spotify.com/track/4sUreUOAY8aJEGxqPwIWI9",
        "https://open.spotify.com/track/51eSHglvG1RJXtL3qI5trr",
        "https://open.spotify.com/track/4hYwvlL0mD5hJH3IyDAGSJ",
        "https://open.spotify.com/track/5BZsQlgw21vDOAjoqkNgKb",
        "https://open.spotify.com/track/1UPB5rYJ0bzn6mNSoAHrZC",
        "https://open.spotify.com/track/0q6LuUqGLUiCPP1cbdwFs3",
        "https://open.spotify.com/track/7uJUDd92ZfawO5clVSY0dq",
        "https://open.spotify.com/track/6G9YlbU3ByPJQvOFDRdwyM",
        "https://open.spotify.com/track/7HXUFIILHAhS6esiRy5Ibz",
        "https://open.spotify.com/track/53iuhJlwXhSER5J2IYYv1W",
        "https://open.spotify.com/track/0RiRZpuVRbi7oqRdSMwhQY",
        "https://open.spotify.com/track/7e7JVMegy4WBMnzuZE9Srq",
        "https://open.spotify.com/track/43iIQbw5hx986dUEZbr3eN",
        "https://open.spotify.com/track/2ipIPsgrgd0j2beDf4Ki70",
        "https://open.spotify.com/track/36vmaZyO0iAE6FZ7287fg2",
        "https://open.spotify.com/track/4GfK1qOF3uBWidbPlTCQRL",
        "https://open.spotify.com/track/63ZoAAduWDVqAXXKz0k9XN",
        "https://open.spotify.com/track/0BEwBflam3FG1sjoVDrCuN",
        "https://open.spotify.com/track/1csKczcJqOSdK8JriLMpDW",
        "https://open.spotify.com/track/3ld1FzyNgpZwGn4h9cOXrq",
        "https://open.spotify.com/track/59c2xv2kMzYM6HR9oY6BIa",
        "https://open.spotify.com/track/1k68vKHNQXU5CHqcM7Yp7N",
        "https://open.spotify.com/track/5rc7178sa2YRDlBFBHY0e8",
        "https://open.spotify.com/track/2nGFzvICaeEWjIrBrL2RAx",
        "https://open.spotify.com/track/3puYuuZ7lmlTjIgXBOT01k",
        "https://open.spotify.com/track/03bTIHJElXZ0O0jqOQvAbY",
        "https://open.spotify.com/track/0iIcuwia47B5bzjVpyUwyI",
        "https://open.spotify.com/track/2dIBMHByUGcNPzmYBJ6OAj",
        "https://open.spotify.com/track/6cLrGfKIIRHYQw7S0mCDhA",
        "https://open.spotify.com/track/3HVcXSx8qNN4zrOkbaADe9",
        "https://open.spotify.com/track/0VxocBntP1XTZRsR9ZURPS",
        "https://open.spotify.com/track/4mf6HE25CkxeezcdWyfUGO",
        "https://open.spotify.com/track/5qMjtrGnezsafpH4oqg7oU",
        "https://open.spotify.com/track/3sICyTPASesVzpfGc1nM2t",
        "https://open.spotify.com/track/4u2b3QdJ6FkyaaTK0TrRQR",
        "https://open.spotify.com/track/2GViQ70Qunna09ZLUFcwdB",
        "https://open.spotify.com/track/6lfxq3CG4xtTiEg7opyCyx",
        "https://open.spotify.com/track/34R8feNZiVrW5OkIl55VCq",
        "https://open.spotify.com/track/284RvSLuEQ2a7udb33qysA",
        "https://open.spotify.com/track/1cPtMErymxlrj7pssAB03r",
        "https://open.spotify.com/track/53AwNAXOEw3H2vEB2HKIJx",
        "https://open.spotify.com/track/4p5ljk84eZ5OKAA8Vfeteu",
        "https://open.spotify.com/track/4pmbFlRamoEKgOJjkVW6JY",
        "https://open.spotify.com/track/73XxBGbtoO3vTuV8lmv96Q",
        "https://open.spotify.com/track/5cLOXwr2i1xpkick9DGGOJ",
        "https://open.spotify.com/track/3Hvg5tRKsQlX25wYwgMF9p",
        "https://open.spotify.com/track/3eWS7zJviX0aRfQgyPB54G",
        "https://open.spotify.com/track/4P6n0udLAnmCNXVcobYbsK",
        "https://open.spotify.com/track/4nKnOIDXFjRSMG4vkXDwzY",
        "https://open.spotify.com/track/5royC4vK6AQGfkRwbnL0Qa",
        "https://open.spotify.com/track/3hXsfPCNGZnZx0l4AYvh8E",
        "https://open.spotify.com/track/55uIELYi6Ykc2YVVOe68xx"
    )
}
